color/urls.py
from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.dashboard, name="dashboard"),
    path('login/', views.login_user, name="login_user"),
    path('register/', views.regsiter_user, name="register_user"),
    path('about-us/', views.about, name="about_us"),
    path('collaborate/', views.collaborate, name="collaborate"),
    path('membership/', views.membership, name="membership"),
    path('product/<int:id>/', views.product_details, name="product-details"),
    path('search/<str:cat>/<int:id>', views.search, name="search"),
    path('add-to-cart/', views.add_to_cart, name="cart"),
    path('my-designs/', views.my_designs, name='my-designs'),
    path('my-products/', views.user_products, name='my-products'),
    path('my-commission/', views.user_commission, name='my-commission'),
    path('upload-design/', views.upload_design, name="upload-design"),
    path('my-profile/', views.my_profile, name="my-profile"),
    path('add-to-wish-list/', views.wish_list, name="wish-list"),
]

colorcult/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include(('color.urls', 'color'), namespace="color")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

color/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator, EmailValidator, validate_slug, URLValidator

# Create your models here.
class User(AbstractUser):
    gender = models.CharField(max_length=50, default="male")
    is_creator = models.BooleanField(default=False, null=True, blank=True)
    phone_regex = RegexValidator(regex=r'^\d{10,10}$', message="Phone number must be entered in the format: '1234567890'. Up to 10 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=10, blank=True)

    class Meta:
        ordering = ['id']

class Banner(models.Model):
    img_height = models.PositiveIntegerField(default=330)
    img_width = models.PositiveIntegerField(default=330)
    first_image = models.ImageField( upload_to='banner/image/', height_field='img_height', width_field='img_width', max_length=None, blank=False)
    second_image = models.ImageField( upload_to='banner/image/',height_field='img_height', width_field='img_width', max_length=None,  blank=False)
    third_image = models.ImageField( upload_to='banner/image/', height_field='img_height', width_field='img_width', max_length=None, blank=False)
    long_banner_image = models.ImageField( upload_to='banner/image/', height_field='img_height', width_field='img_width', max_length=None, blank=False)

    def __str__(self):
        return str(self.first_image)
    
    class Meta:
        verbose_name = "Banner"
        verbose_name_plural = "Banners"
        ordering = ['id']
    
class HomeBanner(models.Model):
    banner_one = models.ImageField( upload_to='banner/image/', blank=False)
    banner_two = models.ImageField( upload_to='banner/image/', blank=False)
    banner_three = models.ImageField( upload_to='banner/image/', blank=False)
    banner_four = models.ImageField( upload_to='banner/image/', blank=False)
    

    class Meta:
        verbose_name = "HomeBanner"
        verbose_name_plural = "HomeBanners"
        ordering =['id']

    def __str__(self):
        return str(self.id)

class Theme(models.Model):
    theme = models.CharField( max_length=100) 
    date = models.DateTimeField( auto_now=True)
    theme_image = models.FileField( upload_to='product/image/',default="/media/image/temple.png", blank=False)
    class Meta:
        verbose_name = "Theme"
        verbose_name_plural = "Themes"
        ordering = ['id', 'theme', 'date']

    def __str__(self):
        return self.theme

class ThemeCategory(models.Model):
    theme = models.ManyToManyField("Theme", verbose_name="theme_category")
    category = models.CharField( max_length=100)
    date = models.DateTimeField( auto_now=True)
    category_image = models.FileField( upload_to='product/image/',default="/media/image/temple.png", blank=False)
    class Meta:
        verbose_name = "ThemeCategory"
        verbose_name_plural = "ThemeCategorys"
        ordering = [ 'id', 'category', 'date']

    def __str__(self):
        return self.category

class Product(models.Model):
    product_name = models.CharField( max_length=100, default="PUBG Grey T-shirt")
    creator = models.ForeignKey("User", verbose_name="Creator", on_delete=models.CASCADE)
    product_theme = models.ManyToManyField("Theme", verbose_name="Product Theme",  blank=True)
    prodcut_description = models.TextField()
    price = models.PositiveIntegerField()
    cult_member_price = models.PositiveIntegerField()
    product_image = models.FileField( upload_to='product/image/',default="/media/image/temple.png", blank=False)
    product_category = models.ManyToManyField("ThemeCategory", verbose_name="Product Theme Category",  blank=True)
    product_size = models.ManyToManyField("ProductSize", verbose_name="Product Size",  blank=True)
    product_related_to_gender = models.ManyToManyField("Gender", verbose_name="Gender",  blank=True)
    product_page_size = models.ManyToManyField("PageSize", verbose_name="Product Page Size",  blank=True)
    product_frame_size = models.ManyToManyField("FrameSize", verbose_name="Product Frame Size",  blank=True)
    product_color = models.ManyToManyField("Color", verbose_name="Add Hex code only for product")
    date = models.DateTimeField( auto_now=True)
    quantity = models.PositiveIntegerField(default=1)

    class Meta:
        verbose_name = "Product"
        verbose_name_plural = "Product"
        ordering = [ 'id', 'price', 'date']

    def __str__(self):
        return str(self.id)

class Color(models.Model):
    color = models.CharField(max_length=100)
    date = models.DateTimeField( auto_now=True)

    class Meta:
        verbose_name = "COlor"
        verbose_name_plural = "COlors"

    def __str__(self):
        return str(self.color)


class ProductSize(models.Model):
    product_sizes = models.CharField( max_length=100)
    date = models.DateTimeField( auto_now=True)
    class Meta:
        verbose_name = "ProductSize"
        verbose_name_plural = "ProductSizes"
        ordering = [ 'id', 'date']


    def __str__(self):
        return str(self.product_sizes)

class Gender(models.Model):
    product_related_to_gender = models.CharField(max_length=50)
    date = models.DateTimeField( auto_now=True)

    class Meta:
        verbose_name = "Gender"
        verbose_name_plural = "Genders"
        ordering = [ 'id', 'date', 'product_related_to_gender']

    def __str__(self):
        return self.product_related_to_gender

class FrameSize(models.Model):
    size = models.CharField( max_length=50)
    date = models.DateTimeField( auto_now=True)

    class Meta:
        verbose_name = "FrameSize"
        verbose_name_plural = "FrameSizes"
        ordering = [ 'id', 'date', 'size']

    def __str__(self):
        return str(self.size)

class PageSize(models.Model):
    page_size = models.CharField(max_length=50)
    date = models.DateTimeField( auto_now=True)

    class Meta:
        verbose_name = "PageSize"
        verbose_name_plural = "PageSizes"
        ordering = [ 'id', 'date', 'page_size']

    def __str__(self):
        return self.page_size
class Image(models.Model):
    product_for = models.ForeignKey("Product", verbose_name="for_product_image", on_delete=models.CASCADE, default='/media/image/temple.png')
    product_images = models.ImageField( upload_to='product/image/')
    date = models.DateTimeField( auto_now=True)

    class Meta:
        verbose_name = "Image"
        verbose_name_plural = "Images"
        ordering = [ 'id', 'date']

    def __str__(self):
        return str(self.id)
class Cart(models.Model):
    user = models.ForeignKey("User", verbose_name="User", on_delete=models.CASCADE)
    product = models.ForeignKey("Product", verbose_name="Product", on_delete=models.CASCADE)
    date = models.DateTimeField( auto_now=True)

    class Meta:
        verbose_name = "Cart"
        verbose_name_plural = "Carts"

    def __str__(self):
        return str(self.user)
STATUS = [
    ('under_review', 'Under Review'),
    ('accepted', 'Accepted'),
    ('rejected', 'Rejected'),
]
class CreatorDesign(models.Model):
    user = models.ForeignKey("User", verbose_name="Creator User", on_delete=models.CASCADE)
    date = models.DateTimeField( auto_now=True)
    design_description = models.TextField()
    design_name = models.CharField(max_length=50, default="art")
    design_image = models.ImageField( upload_to='product/image/')
    design_status = models.CharField(choices=STATUS, max_length=50, default='under_review')

    class Meta:
        verbose_name = "CreatorDesign"
        verbose_name_plural = "CreatorDesigns"

    def __str__(self):
        return str(self.user)


# PRODUCT_SIZES = [
#     ('-', 'Not Applicable'),
#     ('xs','XS'),
#     ('s','S'),
#     ('m','M'),
#     ('l','L'),
#     ('xl','XL'),
#     ('xxl','XXL'),
# ]

color/forms.py
from django import forms
from .models import Banner, User, CreatorDesign
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import EmailValidator
from django.forms import ModelForm

class RegisterUser(UserCreationForm):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female')
    )
    gender = forms.ChoiceField(choices=GENDER_CHOICES, widget=forms.RadioSelect(),label='Gender')
    is_creator = forms.BooleanField(label='Register as a creator')
    class Meta:
        model = User
        fields = ('phone_number', 'username', 'email', 'first_name', 'last_name', 'is_creator', 'gender') 

class UpdateProfile(forms.ModelForm):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female')
    )
    gender = forms.ChoiceField(choices=GENDER_CHOICES, widget=forms.RadioSelect(),label='Gender')
    class Meta:
        model = User
        fields = ('phone_number', 'username', 'email', 'first_name', 'last_name', 'gender') 

class CreatorDesignForm(forms.ModelForm):
    
    class Meta:
        model = CreatorDesign
        fields = ("design_description", "design_name", "design_image")
 

color/templates/pages/cart.html
{% extends '../base.html' %}
{% block title %}Color Cult | Shopping Cart{% endblock title %}
{% block content %}
<div class="container">
    <h3>Shopping Cart</h3>
    <div class="row">
        <div class="col-md-7">
            Items( {{ object.product_count_in_cart }} )
        </div>
         <div class="col-md-5 text-left">
            Subtotal
             <div>
      <div class="content" style="margin-top: 200px;">
          <div class="content-section" style=" width: 387px; border-color: #996BD1;">
        <div class="card">
          <div class="card-title" style="background: rgba(153, 107, 209, 0.07);width: 387px;height: 67px;">
            <h5 id="1" style="margin-left: 15px; margin-top: 15px;">Order Summary<h5>
           </div>
        <div class="card-body ">
         <div class="card-text">
           <p style="text-align: left;">Cart Total <span id="cart-total" style="text-align: right;">$399</span></p>
           <p class="text-muted" style="text-align: left;">GST<span id="gst">$399</span></p>
           <p style="text-align: left;"> Total Amount<span id="amount">$399</span></p>
           <hr>
           <p style="text-align: left;">Shipping Charges<span id="shipping" style="">FREE</span></p>

           <hr>
           <p style="text-align: left;">Total Payable<span id="payable">$399</span></p>
         </div>
       </div>
      </div>
        <button class="btn btn-class" id="mybtn" style="width: 387px;height: 49px;left: 893px;margin-top: 20px;color: white;background: #996BD1;border: 1px solid rgba(153, 107, 209, 0.3);border-radius: 4px;">Continue</button>
      </div>
    </div>
  </div>
         </div>
    </div>
    <div class="row">
        Pending
        <div class="col-md-6">
            <ul class="ul cart-ul">
            {% for prod in product_object_list %}
                {% for p in prod %}
                    <li>
                        <div class="li-inner">
                            <div class="left-img">
                                <img class="img-fluid" src="{{ p.product_image.url }}">
                            </div>
                            <div class="right-text">
                                <p class="name">{{ p.product_name }}</p>
                                <p class="category">{{ p.product_category.first | join:', ' }}</p>
                                <div class="p-list">
                                    <p>Color: {{ p.product_color.first | join:', ' }}</p>
                                    <p>Size:</p>
                                    <p>Quantity:</p>
                                </div>
                                <div class="r-total">
                                    <span><a>Remove</a></span>
                                    <span>Rs. {{ p.price }}</span>
                                </div>
                            </div>
                        </div>
                    </li>
                {%endfor%}
            {%endfor%}
            </ul>
        </div>
    </div>
</div>
<div class="messages">
    {%if messages %}
        {%for message in messages%}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {%endfor%}
    {%endif%}
</div>
{% endblock %}
cookies madhun id retrive karav lagel list

color/templates/pages/design-upload.html
{% extends '../base.html' %}
{% block title %}Upload Your Design{% endblock title %}
{% load static %}
{% block content %}
    <div class="container">
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}
        <div class="row">
            <div class="col-md-4">
                <img src="{% static 'img/Vector(7).png' %}" style="display: inline-block;margin-left: 100px;margin-top: 100px;">
                <p>
                    We would like you to visit our
                <a style="color:black;" href="#"><b>Submission Guidelines</b></a>
                    for more information.
                </p>
            </div>
            <div class="col-md-6">
                <div class="design-upload">
                    <form method="POST" enctype='multipart/form-data'>
                        {% csrf_token %}
                        {{form}}
                        <button style="width: 169px;height: 33px;left: 889px;top: 404px; color: white; background: #996BD1;
border: 1px solid rgba(153, 107, 209, 0.3);
border-radius: 4px;" type="submit">Upload</button>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

color/templates/pages/user-commission.html
{% extends '../base.html' %}
{% block title %}Color Cult | My Commission{% endblock title %}
{% block content %}
<h3 id="heading">MY COMMISSION</h3>
  <div id="Div1" style="background: #F0F0F0; margin-top: 80px;height: 67px;">
    <img src="#" alt="" id="logo">
    <p style="margin-left: 200px;">Total Commission Amount Till Date: <b> ₹7421.00</b>
    <span style="text-align: right;margin-left: 230px;">Commission Balance:<b> ₹99.00</b>
   <button class="btn btn-class" id="mybtn" data-href="#">Payout</button>
   <a href="#" style="color: black;">Add Banking Details</a></span></p>
  </div>
<div class="container">

    <div id="Div2">
      <center>
        <div id="Div3">
         <table id="myTable" class="table ">
          <thead>
            <tr>
              <th>Date</th>
              <th>Product Name</th>
              <th>Price</th>
              <th>Transaction Type</th>
              <th>Amount</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>12/12/2020</td>
              <td>PUBG White Crop Top</td>
              <td>599.00</td>
              <td>Credit</td>
              <td>59.00</td>
                </tr>
                <tr>
                  <td>12/12/2020</td>
                  <td>PUBG White Crop Top</td>
                  <td>599.00</td>
                  <td>Credit</td>
                  <td>59.00</td>
                    </tr>
                    <tr>
                     <td>12/12/2020</td>
                     <td>PUBG White Crop Top</td>
                     <td>599.00</td>
                     <td>Credit</td>
                     <td>59.00</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </center>
            </div>
          </div>
        </div>
<style type="text/css">
  div#Div2 {
    background-color: white;
    border: 1px;
    border-radius: 8px;
    width: 1032px;
    height: 620px;
    left: 225px;
    top: 104px;
}
div#Div3 {
    width: 900px;
    height: 300px;
    margin-left: 50px;
    margin-right: 30px;
    margin-top: 30px;

    background: rgba(235, 235, 235, 0.08);
    /*border: 1px solid rgba(235, 235, 235, 0.8);
    box-sizing: border-box;*/
    border-radius: 8px;

    font-size: 14px;
    opacity: 0.8;
}
table#myTable {
    border: 1px;
    border-radius: 8px;
    width: 740px;
}

th, td {
  text-align: left;
}
#heading{
    color:#996BD1;font-weight: 600;text-align: center;margin-top:60px;
  }
#mybtn{
  width: 144px;
height: 39px;
margin-left: 30px;
top: 187px;
color: white;
background: #996BD1;
border: 1px solid rgba(153, 107, 209, 0.3);
border-radius: 4px;
}
</style>
</div>
{% endblock %}

color/templates/pages/user-designs.html
{% extends '../base.html' %}
{% block title %}My Designs{% endblock title %}
{% block content %}
<div class="container">
    <h3>My Designs</h3>
    <div class="row">
        <div class="col-md-6">
            <p>Total ({{ get_current_login_user_design_count }})
        </div>
         <div class="col-md-6">
            <a type="button" href="{% url 'color:upload-design' %}" class="btn btn-info" style="width: 119px;background: #996BD1;border: 1px solid rgba(153, 107, 209, 0.3);border-radius: 4px;">+ Upload</a>
        </div>
    </div>
    <div class="row">
    {% for get_current_login_user_design in get_current_login_user_designs %}
        <div class="col-md-3 designs-row">
            <div class="img-wrap">
                <img src="{{ get_current_login_user_design.design_image.url }}" class="img-fluid">
            </div>
            <div class="text-wrap">
                <h4>{{ get_current_login_user_design.design_name }}</h4>
                <p>Status:<span>{{ get_current_login_user_design.get_design_status_display }}</span></p>
            </div>
        </div>
    {% endfor %}
    </div>
</div>
{% endblock %}

color/templates/pages/user-product.html
{% extends '../base.html' %}
{% block title %}My Products{% endblock title %}
{% block content %}
<div class="container">
    <h3>My Products</h3>
    <div class="row">
        <div class="col-md-6">
            <p>Total ({{ get_user_product_count }})
        </div>
    </div>
    <div class="row">
    {% for get_user_product in get_user_products %}
        <div class="col-md-3 designs-row">
            <div class="img-wrap">
                <img src="{{ get_user_product.product_image.url }}" class="img-fluid">
            </div>
            <div class="row">
                <div class="col-md-6">
                    <h4>{{ get_user_product.product_category.first | join:', ' }}</h4>
                </div>
                <div class="col-md-6">
                    <p>{{ get_user_product.product_theme.first | join:', ' }}</p>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
</div>
{% endblock %}

color/templates/pages/user-profile.html
{% extends '../base.html' %}
{% block title %}Color Cult | My Profile{% endblock title %}
{% block content %}
    {% load static %}
    <section id="home-banner">
        <div class="home-banner-slider">
            <div class="home-img">
                <img class="img-fluid" src="{{ get_home_banners.banner_one.url }}">
            </div>
            <div class="home-img">
                <img class="img-fluid" src="{{ get_home_banners.banner_two.url }}">
            </div>
            <div class="home-img">
                <img class="img-fluid" src="{{ get_home_banners.banner_three.url }}">
            </div>
            <div class="home-img">
                <img class="img-fluid" src="{{ get_home_banners.banner_four.url }}">
            </div>
        </div>
    </section>
    <div class="container">
        <h3>My Profile</h3>
        <div class="tab-panel">
            <div class="tab">
                <button class="tablinks active" onclick="openCity(event, 'personal_details')">Personal Details</button>
                <button class="tablinks" onclick="openCity(event, 'address_details')">Address Details</button>
                <button class="tablinks" onclick="openCity(event, 'banking_details')">Banking Details</button>
                <button class="tablinks" onclick="openCity(event, 'change_password')">Change Password</button>
            </div>

            <div id="personal_details" class="tabcontent">
                <form method="POST">
                    {% csrf_token %}
                    {{ form }}
                    <button type="submit" name="update_profile" id="update_profile" class="btn btn-info">Update</button>
                </form>
            </div>

            <div id="address_details" class="tabcontent">
                <h3>Paris</h3>
                <p>Paris is the capital of France.</p>
            </div>

            <div id="banking_details" class="tabcontent">
                <h3>Tokyo</h3>
                <p>Tokyo is the capital of Japan.</p>
            </div>
            <div id="change_password" class="tabcontent">
                <form method="POST">
                    {{ change_pass }}
                    <button type="submit" name="update_pass" id="update_pass" class="btn btn-info" >Update Password</button>
                </form>
            </div>
        </div>
    </div>
<script>
function openCity(evt, cityName) {
console.log(cityName)
  var i, tabcontent, tablinks;
  tabcontent = document.getElementsByClassName("tabcontent");
  for (i = 0; i < tabcontent.length; i++) {
    tabcontent[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablinks");
  for (i = 0; i < tablinks.length; i++) {
    tablinks[i].className = tablinks[i].className.replace(" active", "");
  }
  document.getElementById(cityName).style.display = "block";
  evt.currentTarget.className += " active";
}

// Get the element with id="defaultOpen" and click on it
document.getElementById("defaultOpen").click();
</script>
<style>#update_pass{width: auto;background: #996BD1;border: 1px solid rgba(153, 107, 209, 0.3);border-radius: 4px;}
#update_profile{width: auto;background: #996BD1;border: 1px solid rgba(153, 107, 209, 0.3);border-radius: 4px;}</style>
{% endblock %}

color/templates/pages/wish-list.html
{% extends '../base.html' %}
{% block title %}Color Cult | My Profile{% endblock title %}
{% block content %}
    {% load static %}
    <section id="home-banner">
        <div class="home-banner-slider">
            <div class="home-img">
                <img class="img-fluid" src="{{ get_home_banners.banner_one.url }}">
            </div>
            <div class="home-img">
                <img class="img-fluid" src="{{ get_home_banners.banner_two.url }}">
            </div>
            <div class="home-img">
                <img class="img-fluid" src="{{ get_home_banners.banner_three.url }}">
            </div>
            <div class="home-img">
                <img class="img-fluid" src="{{ get_home_banners.banner_four.url }}">
            </div>
        </div>
    </section>
    <div class="container">
      <h3>My Wish List</h3>
        <div class="row">
            <div class="col-md-12">
                Items( {{ product_count_in_cart }} )
            </div>
        </div>
    </div>
{% endblock %}