color/urls.py
from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.dashboard, name="dashboard"),
    path('login/', views.login_user, name="login_user"),
    path('register/', views.regsiter_user, name="register_user"),
    path('about-us/', views.about, name="about_us"),
    path('collaborate/', views.collaborate, name="collaborate"),
    path('membership/', views.membership, name="membership"),
    path('product/<int:id>/', views.product_details, name="product-details"),
    path('search/<str:cat>/<int:id>', views.search, name="search"),
    path('add-to-cart/', views.add_to_cart, name="cart"),
    path('my-designs/', views.my_designs, name='my-designs'),
    path('my-products/', views.user_products, name='my-products'),
    path('my-commission/', views.user_commission, name='my-commission'),
    path('upload-design/', views.upload_design, name="upload-design"),
    path('my-profile/', views.my_profile, name="my-profile"),
    path('add-to-wish-list/', views.wish_list, name="wish-list"),
]

colorcult/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include(('color.urls', 'color'), namespace="color")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

color/forms.py
from django import forms
from .models import Banner, User, CreatorDesign
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import EmailValidator
from django.forms import ModelForm

class RegisterUser(UserCreationForm):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female')
    )
    gender = forms.ChoiceField(choices=GENDER_CHOICES, widget=forms.RadioSelect(),label='Gender')
    is_creator = forms.BooleanField(label='Register as a creator')
    class Meta:
        model = User
        fields = ('phone_number', 'username', 'email', 'first_name', 'last_name', 'is_creator', 'gender') 

class UpdateProfile(forms.ModelForm):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female')
    )
    gender = forms.ChoiceField(choices=GENDER_CHOICES, widget=forms.RadioSelect(),label='Gender')
    class Meta:
        model = User
        fields = ('phone_number', 'username', 'email', 'first_name', 'last_name', 'gender') 

class CreatorDesignForm(forms.ModelForm):
    
    class Meta:
        model = CreatorDesign
        fields = ("design_description", "design_name", "design_image")
 

color/views.py
from django.shortcuts import render, redirect
from .models import Banner, HomeBanner, ThemeCategory, Theme, Product, Image, Cart, User, CreatorDesign
from .forms import RegisterUser, CreatorDesignForm, UpdateProfile
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.http import JsonResponse
from django.contrib.auth import login
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import HttpResponse
from django.views import View


# Project Views


def wish_list(request):
    response = HttpResponse('adding product to wish list')
    print(response)
    if request.method == 'POST':
        wish_id = request.POST.get('data_id')
        print(request.POST.get('data_id'))
        if 'wish_id' in request.COOKIES:
            wish_id = request.COOKIES['wish_id']
            counter = wish_id.split('|')
            ids = set(counter)
            print('wish ids {}'.format(ids))
            print('wish id {}'.format(wish_id))
            wish_object_id_list = []
            for prod_id in ids:
                product = Product.objects.filter(id=prod_id)
                wish_object_id_list.append(product)
            wish_count = len(set(counter))
        else:
            wish_count = 1
        '''adding product id to wish list'''
        print('wish {}'.format(request.COOKIES['wish_id']))
        if 'wish_id' in request.COOKIES:
            wish_id = request.COOKIES['wish_id']
            if wish_id == "":
                wish_id = str(wish_id)
            else:
                wish_id = wish_id + "|" + str(wish_id)
            response.set_cookie('wish_id', wish_id)
        else:
            response.set_cookie('wish_id', wish_id)
            print('wish response {}'.format(wish_id))
    # return JsonResponse({'status': 'ok'})
    return render(request, template_name="pages/wish-list.html", context={})


'''Adding products to Cart'''
'''def add_to_cart(request):
    print('cart {}'.format(request.COOKIES))
    response = HttpResponse('adding product to cart!')
    # for cart counter, fetching products ids added by customer from cookies
    if request.method == 'POST': 
        product_id = request.POST.get('data_id')
        cart = request.session.get('cart')

        if 'product_ids' in request.COOKIES:
            product_ids = request.COOKIES['product_ids'] 
            counter = product_ids.split('|')
            ids = set(counter)
            product_object_list = []
            for prod_id in ids:
                product = Product.objects.filter(id=prod_id)
                product_object_list.append(product)
            product_count_in_cart = len(set(counter))
        else:
            product_count_in_cart = 1
        print(product_id)
        #response = render(request, template_name="pages/cart.html")
        #return redirect('cart')
        #, context={'product_object_list': product_object_list,'product_count_in_cart': product_count_in_cart}
        #adding product id to cookies list is empty
        if 'product_ids' in request.COOKIES: 
            product_ids = request.COOKIES['product_ids']
            if product_ids == "":
                product_ids = str(product_id)
            else:
                product_ids = product_ids+"|"+str(product_id)
            response.set_cookie('product_ids', product_ids)
        else:
            response.set_cookie('product_ids', product_id)

        product = Product.objects.get(id=product_id)
        messages.info(request, str(product.product_name) + ' added to cart successfully!')
   # return JsonResponse({'status': 'ok'})
    return render(request, template_name="pages/cart.html")'''


def my_profile(request):
    get_home_banners = HomeBanner.objects.first()
    get_user = User.objects.get(id=request.user.id)
    change_pass = PasswordChangeForm(request.user)
    form = UpdateProfile(request.POST or None, instance=get_user)
    if request.method == "POST" and 'update_profile' in request.POST:
        if form.is_valid():
            form.save()
            return redirect('color:my-profile')

    if request.method == 'POST' and 'update_pass' in request.POST:
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('color:my-profile')
        else:
            messages.error(request, 'Please correct the error below.')
    return render(request, template_name="pages/user-profile.html",
                  context={'get_home_banners': get_home_banners, 'form': form, 'change_pass': change_pass})


def user_commission(request):
    print(request.COOKIES)
    return render(request, template_name="pages/user-commission.html", context={})


def user_products(request):
    get_user_products = Product.objects.filter(creator_id=request.user.id)
    get_user_product_count = Product.objects.filter(creator_id=request.user.id).count()
    return render(request, template_name="pages/user-product.html",
                  context={'get_user_products': get_user_products, 'get_user_product_count': get_user_product_count})


def upload_design(request):
    creator_design_form = CreatorDesignForm(request.POST or None)
    if request.method == "POST":
        creator_design_form = CreatorDesignForm(request.POST or None, request.FILES)
        print(creator_design_form)
        if creator_design_form.is_valid():
            creator_design_form = creator_design_form.save(commit=False)
            creator_design_form.user = request.user
            creator_design_form.design_status = 'under_review'
            creator_design_form.save()
            return redirect('color:my-designs')
    return render(request, template_name="pages/design-upload.html", context={"form": creator_design_form})


def my_designs(request):
    get_current_login_user_designs = CreatorDesign.objects.filter(user=request.user)
    get_current_login_user_design_count = CreatorDesign.objects.filter(user=request.user).count()

    return render(request, template_name="pages/user-designs.html",
                  context={'get_current_login_user_designs': get_current_login_user_designs,
                           'get_current_login_user_design_count': get_current_login_user_design_count})


def regsiter_user(request):
    form = RegisterUser(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password2']
            form = form.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('color:dashboard')
    return render(request, template_name="registration/register.html", context={'form': form})


def login_user(request):
    logout(request)
    username = password = ''
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('color:dashboard')
    else:
        return redirect('color:dashboard')
    return render(request, template_name='dashboard.html', context={})


def dashboard(request):
    print(request.session)
    # response = HttpResponse('adding product to wish list')
    # value1 = request.COOKIES['pr']
    # print('cookie {}'.format(value1))
    get_replaceable_banner = Banner.objects.first()
    get_home_banners = HomeBanner.objects.first()
    get_all_theme_categories = ThemeCategory.objects.all()
    get_all_themes = Theme.objects.all()
    get_six_theme_categories = ThemeCategory.objects.all().order_by('-date')[:6]
    get_six_themes = Theme.objects.all().order_by('-date')[:6]
    get_cult_favs = Product.objects.all().order_by('-date')[:4]
    # form = AuthenticationForm()
    # request.login_form = form
    response = render(request, template_name='dashboard.html',
                      context={'get_all_theme_categories': get_all_theme_categories,
                               'get_replaceable_banners': get_replaceable_banner, 'get_home_banners': get_home_banners,
                               'get_all_themes': get_all_themes, 'get_cult_favs': get_cult_favs,
                               'get_six_themes': get_six_themes, 'get_six_theme_categories': get_six_theme_categories})
    # response.set_cookie('pr', '123456789')
    return response


def product_details(request, id):
    get_single_product = Product.objects.get(id=id)
    get_images = Image.objects.filter(product_for=get_single_product.id)
    single_cat = []
    single_theme = []
    for get_cat in get_single_product.product_category.all():
        single_cat.append(get_cat)

    for get_theme in get_single_product.product_theme.all():
        single_theme.append(get_theme)
    get_similar_products_by_category = Product.objects.filter(product_category=single_cat[0]).order_by('-id')[:4]
    get_similar_products_by_theme = Product.objects.filter(product_theme=single_theme[0]).order_by('-id')[:4]
    return render(request, template_name="pages/product-details.html",
                  context={'get_single_product': get_single_product, 'get_images': get_images,
                           'get_similar_products': get_similar_products_by_category,
                           'get_similar_products_by_theme': get_similar_products_by_theme})


def search(request, cat, id):
    get_all_theme_categories = ThemeCategory.objects.all()

color/templates/dashboard.html
{% extends 'base.html' %}
{% block title %} Color Cult | Home {% endblock title %}
{% block content %}
    {% load static %}
    
    <section id="home-banner">
        <div class="home-banner-slider">
            <div class="home-img">
                <img class="img-fluid" src="{{ get_home_banners.banner_one.url }}">
            </div>
            <div class="home-img">
                <img class="img-fluid" src="{{ get_home_banners.banner_two.url }}">
            </div>
            <div class="home-img">
                <img class="img-fluid" src="{{ get_home_banners.banner_three.url }}">
            </div>
            <div class="home-img">
                <img class="img-fluid" src="{{ get_home_banners.banner_four.url }}">
            </div>
        </div>
    </section>
    <section>
      <div class="">
        <div class="section-title ups">
          <span>Shop by themes</span>
        </div>
        <ul class="ul home-prod-menu">
          {% for theme in get_six_themes %}
            <li>
              <a href="{% url 'color:search' theme.theme theme.id %}">
                <img src="{{ theme.theme_image.url }}" title="{{ theme.theme }}" alt="{{ theme.theme }}" class="img-fluid">
              </a>
            </li>
          {% endfor %}
        </ul>
        <div class="section-title up">
          <span>Shop by products</span>
        </div>
        <ul class="ul home-prod-menu bottom">
          {% for category in get_six_theme_categories %}
            <li>
              <a href="{% url 'color:search' category.category category.id %}">
                <img src="{{ category.category_image.url }}" title="{{ category.category }}" alt="{{ category.category }}" class="img-fluid">
              </a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </section>
    <section id="replaceble_banners">
      <div class="container">
        <div class="row">        
          <div class="col-lg-4 col-md-4 col-sm-12 mb-4">
            <img class="img-fluid" src="{{get_replaceable_banners.first_image.url}}">
          </div>
          
          <div class="col-lg-4 col-md-4 col-sm-12 mb-4">
            <img class="img-fluid" src="{{get_replaceable_banners.second_image.url}}">
          </div>
          <div class="col-lg-4 col-md-4 col-sm-12 mb-4">
            <img class="img-fluid" src="{{get_replaceable_banners.third_image.url}}">
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <img class="img-fluid" src="{{get_replaceable_banners.long_banner_image.url}}">
          </div>
        </div>
      </div>
    </section>
    <section id="cult-fav">
      <div class="container">
        <div class="section-title">
          <span>Cult favourites</span>
        </div>
        <div class="prod-wrap">
          <div class="row mb-4">
          
            {% for get_cult_fav in get_cult_favs %}
              <div class="col-md-3">  
                <div class="prod-outer-wrap">
                  <a class="prod-a" href="{% url 'color:product-details' get_cult_fav.id %}">
                    <div class="prod-img-wrap">
                      <img src="{{ get_cult_fav.product_image.url }}" alt="{{ get_cult_fav.prodcut_description }}" class="img-fluid h-100">
                    </div>
                    <div class="prod-text">
                      <div class="prod-cat"> {{ get_cult_fav.product_theme.all | join:', ' }} </div>
                      <div class="prod-theme"> {{ get_cult_fav.product_category.all | join:', ' }} </div>
                    </div>
                    <div class="pricing">
                      <div class="normal-price">Rs. {{ get_cult_fav.price }} </div>
                      <div class="cult-price"><span>Rs. {{ get_cult_fav.cult_member_price }}</span> for Cult memebers</div>
                    </div>
                  </a>
                  <div class="design-by"> Design by <a class="creator">{{ get_cult_fav.creator }}</a></div>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </section>
    <section id="your-design"></section>
{% endblock %}